main=~/PycharmProjects/pynet/main.py

#CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/scz_prediction/tmp/ --exp_name ResNet34_FinedTuned_Age_Sex_balanced -b 8 --nb_folds 5 --net resnet34 --lr 1e-4 --nb_epochs 100 --with_test --pretrained_path /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet34_Age_Sex_WithoutFC_0_epoch_99.pth  &> resnet34_b.txt &
#CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/tmp/ --exp_name Test_ResNet18_Age_Sex -b 8 --nb_folds 1 --net resnet18 --lr 1e-4 --nb_epochs 100 --test --pretrained_path /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/tmp/ResNet18_Age_Sex_0_epoch_99.pth  &> resnet18.txt &
#CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/tmp/ --exp_name Test_ResNet50_Age_Sex -b 8 --nb_folds 1 --net resnet50 --lr 1e-4 --nb_epochs 100 --test --pretrained_path /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/tmp/ResNet50_Age_Sex_0_epoch_99.pth  &> resnet50.txt &
#CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/tmp/ --exp_name Test_ResNet101_Age_Sex -b 8 --nb_folds 1 --net resnet101 --lr 1e-4 --nb_epochs 100 --test --pretrained_path /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/tmp/ResNet101_Age_Sex_0_epoch_99.pth  &> resnet101.txt &
#CUDA_VISIBLE_DEVICES=2 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/tmp/ --exp_name Test_ResNeXt50_Age_Sex -b 8 --nb_folds 1 --net resnext50 --lr 1e-4 --nb_epochs 100 --test --pretrained_path /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/tmp/ResNeXt50_Age_Sex_0_epoch_99.pth  &> resnext50.txt &
#CUDA_VISIBLE_DEVICES=2 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/tmp/ --exp_name Test_VGG11_Age_Sex -b 8 --nb_folds 1 --net vgg11 --lr 1e-4 --nb_epochs 100 --test --pretrained_path /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/tmp/VGG11_Age_Sex_0_epoch_99.pth  &> vgg11.txt &
#CUDA_VISIBLE_DEVICES=2 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/tmp/ --exp_name Test_DenseNet121_Age_Sex -b 8 --nb_folds 1 --net densenet121 --lr 1e-4 --nb_epochs 100 --test --pretrained_path /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/tmp/DenseNet121_Age_Sex_0_epoch_99.pth  &> densenet121.txt &
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/tmp/ --exp_name Test_VGG16_Age_Sex -b 8 --nb_folds 1 --net vgg16 --lr 1e-4 --nb_epochs 100 --test --pretrained_path /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/tmp/VGG16_Age_Sex_0_epoch_99.pth  &> vgg16.txt &

#CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/scz_prediction/tmp/ --exp_name Test_ResNet34_Action_Recognition_DA_fold0_epoch99 -b 8 --nb_folds 5 --net resnet34 --lr 1e-4 --nb_epochs 100 --test --pretrained_path /neurospin/psy_sbox/bd261576/checkpoints/scz_prediction/tmp/ResNet34_Action_Recognition_Pretrained_Data_Augmented_0_epoch_99.pth &> resnet34_0.txt &
#CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/scz_prediction/tmp/ --exp_name Test_ResNet34_Action_Recognition_DA_fold1_epoch99 -b 8 --nb_folds 5 --net resnet34 --lr 1e-4 --nb_epochs 100 --test --pretrained_path /neurospin/psy_sbox/bd261576/checkpoints/scz_prediction/tmp/ResNet34_Action_Recognition_Pretrained_Data_Augmented_1_epoch_99.pth&> resnet34_1.txt &
#CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/scz_prediction/tmp/ --exp_name Test_ResNet34_Action_Recognition_DA_fold2_epoch99 -b 8 --nb_folds 5 --net resnet34 --lr 1e-4 --nb_epochs 100 --test --pretrained_path /neurospin/psy_sbox/bd261576/checkpoints/scz_prediction/tmp/ResNet34_Action_Recognition_Pretrained_Data_Augmented_2_epoch_99.pth &> resnet34_2.txt &
#CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/scz_prediction/tmp/ --exp_name Test_ResNet34_Action_Recognition_DA_fold3_epoch99 -b 8 --nb_folds 5 --net resnet34 --lr 1e-4 --nb_epochs 100 --test --pretrained_path /neurospin/psy_sbox/bd261576/checkpoints/scz_prediction/tmp/ResNet34_Action_Recognition_Pretrained_Data_Augmented_3_epoch_99.pth &> resnet34_3.txt &
#CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/scz_prediction/tmp/ --exp_name Test_ResNet34_Action_Recognition_DA_fold4_epoch99 -b 8 --nb_folds 5 --net resnet34 --lr 1e-4 --nb_epochs 100 --test --pretrained_path /neurospin/psy_sbox/bd261576/checkpoints/scz_prediction/tmp/ResNet34_Action_Recognition_Pretrained_Data_Augmented_4_epoch_99.pth &> resnet34_4.txt &

#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/scz_prediction/tmp/ --exp_name PsyNet_Es_ResNet_Eu_fixed -b 8 --nb_folds 5 --net psy_net --lr 1e-4 --nb_epochs 100 --pretrained_path /neurospin/psy_sbox/bd261576/checkpoints/GAN/AlphaWGAN_Pretrained_epoch8.pth &> psy_net_Es_resnet.txt &

CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/scz_prediction/tmp/ --exp_name PsyNet_ResNet_Action_Recognition_Pretraining --pretrained_path /neurospin/psy_sbox/bd261576/checkpoints/GAN/AlphaWGAN_epoch8_ResNet34_ActionRecognition.pth -b 8 --nb_folds 5 --net psy_net --lr 1e-4 --nb_epochs 100  &> psynet.txt &
