main=~/PycharmProjects/pynet/main.py

#CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/scz_prediction/tmp/ --exp_name ResNet34_FinedTuned_Age_Sex_balanced -b 8 --nb_folds 5 --net resnet34 --lr 1e-4 --nb_epochs 100 --with_test --pretrained_path /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet34_Age_Sex_WithoutFC_0_epoch_99.pth  &> resnet34_b.txt &
#CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/tmp/ --exp_name Test_ResNet18_Age_Sex -b 8 --nb_folds 1 --net resnet18 --lr 1e-4 --nb_epochs 100 --test --pretrained_path /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/tmp/ResNet18_Age_Sex_0_epoch_99.pth  &> resnet18.txt &
#CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/tmp/ --exp_name Test_ResNet50_Age_Sex -b 8 --nb_folds 1 --net resnet50 --lr 1e-4 --nb_epochs 100 --test --pretrained_path /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/tmp/ResNet50_Age_Sex_0_epoch_99.pth  &> resnet50.txt &
#CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/tmp/ --exp_name Test_ResNet101_Age_Sex -b 8 --nb_folds 1 --net resnet101 --lr 1e-4 --nb_epochs 100 --test --pretrained_path /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/tmp/ResNet101_Age_Sex_0_epoch_99.pth  &> resnet101.txt &
#CUDA_VISIBLE_DEVICES=2 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/tmp/ --exp_name Test_ResNeXt50_Age_Sex -b 8 --nb_folds 1 --net resnext50 --lr 1e-4 --nb_epochs 100 --test --pretrained_path /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/tmp/ResNeXt50_Age_Sex_0_epoch_99.pth  &> resnext50.txt &
#CUDA_VISIBLE_DEVICES=2 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/tmp/ --exp_name Test_VGG11_Age_Sex -b 8 --nb_folds 1 --net vgg11 --lr 1e-4 --nb_epochs 100 --test --pretrained_path /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/tmp/VGG11_Age_Sex_0_epoch_99.pth  &> vgg11.txt &
#CUDA_VISIBLE_DEVICES=2 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/tmp/ --exp_name Test_DenseNet121_Age_Sex -b 8 --nb_folds 1 --net densenet121 --lr 1e-4 --nb_epochs 100 --test --pretrained_path /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/tmp/DenseNet121_Age_Sex_0_epoch_99.pth  &> densenet121.txt &
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/tmp/ --exp_name Test_VGG16_Age_Sex -b 8 --nb_folds 1 --net vgg16 --lr 1e-4 --nb_epochs 100 --test --pretrained_path /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/tmp/VGG16_Age_Sex_0_epoch_99.pth  &> vgg16.txt &

#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/scz_prediction/Benchmark_Transfer/No_Pretraining/Basic_With_Flip/ColeNet/ --exp_name ColeNet_Scratch -b 8 --nb_folds 1 --db scz_kfolds --sampler weighted_random --stratify_label diagnosis --labels diagnosis --net cole_net --test --lr 1e-4 --nb_epochs 100  &> cole_net.txt &
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/scz_prediction/Benchmark_Transfer/Sex_Age_Pretraining/Weigthed_Loss --exp_name ResNet34_Sex_Age_Pretraining -b 8 --nb_folds 5 --net resnet34 --lr 1e-4 --pretrained_path /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet34_Age_Sex_WithoutFC_0_epoch_99.pth --nb_epochs 100  &> resnet34_sex_age.txt &
#CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/scz_prediction/Benchmark_Transfer/Action_Recognition_Pretraining/Weighted_Loss --exp_name ResNet34_Action_Recognition -b 8 --nb_folds 5 --net resnet34 --lr 1e-4 --pretrained_path /neurospin/psy_sbox/bd261576/checkpoints/pretrained_3D_resnet/resnet-34-without-fc.pth --nb_epochs 100  &> resnet34_action_recognition.txt &


## LightResNet34
#CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/LightResNet34/N_100 --exp_name Light_ResNet34_Age_HCP_IXI -b 8 --nb_folds 10 --net light_resnet34 --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 100 --N_train_max 100 &> light_resnet34_N100.txt &
#CUDA_VISIBLE_DEVICES=2 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/LightResNet34/N_300 --exp_name Light_ResNet34_Age_HCP_IXI -b 8 --nb_folds 10 --net light_resnet34 --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 100 --N_train_max 300 &> light_resnet34_N300.txt &
#CUDA_VISIBLE_DEVICES=3 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/LightResNet34/N_500 --exp_name Light_ResNet34_Age_HCP_IXI -b 8 --nb_folds 5 --net light_resnet34 --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 100 --N_train_max 500 &> light_resnet34_N500.txt &
#
#ColeNet
#Sex problem
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ColeNet/N_100/Sex --exp_name ColeNet_Sex_HCP_IXI -b 8 --nb_folds 10 --net cole_net --db healthy --sampler random --labels sex --stratify_label site --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 100 &> colenet_sex_100.txt &
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ColeNet/N_300/Sex --exp_name ColeNet_Sex_HCP_IXI -b 8 --nb_folds 10 --net cole_net --db healthy --sampler random --labels sex --stratify_label site --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 300 &> colenet_sex_300.txt &
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ColeNet/N_500/Sex --exp_name ColeNet_Sex_HCP_IXI -b 8 --nb_folds 5 --net cole_net --db healthy --sampler random --labels sex --stratify_label site --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 500 &> colenet_sex_500.txt &
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ColeNet/N_1000/Sex --exp_name ColeNet_Sex_HCP_IXI -b 8 --nb_folds 5 --net cole_net --db healthy --sampler random --labels sex --stratify_label site --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 1000 &> colenet_sex_1000.txt &
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ColeNet/N_1600/Sex --exp_name ColeNet_Sex_HCP_IXI -b 8 --nb_folds 1 --net cole_net --db healthy --sampler random --labels sex --stratify_label site --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 1600 &> colenet_sex_1600.txt &
## Age problem
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ColeNet/N_100/Age --exp_name ColeNet_Age_HCP_IXI -b 8 --nb_folds 10 --net cole_net --db healthy --sampler random --labels age --stratify_label age --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 100 &> colenet_age_100.txt &
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ColeNet/N_300/Age --exp_name ColeNet_Age_HCP_IXI -b 8 --nb_folds 10 --net cole_net --db healthy --sampler random --labels age --stratify_label age --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 300 &> colenet_age_300.txt &
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ColeNet/N_500/Age --exp_name ColeNet_Age_HCP_IXI -b 8 --nb_folds 5 --net cole_net --db healthy --sampler random --labels age --stratify_label age --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 500 &> colenet_age_500.txt &
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ColeNet/N_1000/Age --exp_name ColeNet_Age_HCP_IXI -b 8 --nb_folds 5 --net cole_net --db healthy --sampler random --labels age --stratify_label age --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 1000 &> colenet_age_1000.txt &
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ColeNet/N_1600/Age --exp_name ColeNet_Age_HCP_IXI -b 8 --nb_folds 1 --net cole_net --db healthy --sampler random --labels age --stratify_label age --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --N_train_max 1600 &> colenet_age_1600.txt &

##
#### ResNet34
## Sex problem
#CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet34/N_100/Sex --exp_name ResNet34_Sex_HCP_IXI -b 8 --nb_folds 10 --net resnet34 --db healthy --sampler random --labels sex --stratify_label site --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 100 &> resnet34_sex_100.txt &
#CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet34/N_300/Sex --exp_name ResNet34_Sex_HCP_IXI -b 8 --nb_folds 10 --net resnet34 --db healthy --sampler random --labels sex --stratify_label site --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 300 &> resnet34_sex_300.txt &
#CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet34/N_500/Sex --exp_name ResNet34_Sex_HCP_IXI -b 8 --nb_folds 5 --net resnet34 --db healthy --sampler random --labels sex --stratify_label site --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 500 &> resnet34_sex_500.txt &
#CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet34/N_1000/Sex --exp_name ResNet34_Sex_HCP_IXI -b 8 --nb_folds 5 --net resnet34 --db healthy --sampler random --labels sex --stratify_label site --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 1000 &> resnet34_sex_1000.txt &
#CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet34/N_1600/Sex --exp_name ResNet34_Sex_HCP_IXI -b 8 --nb_folds 1 --net resnet34 --db healthy --sampler random --labels sex --stratify_label site --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 1600 &> resnet34_sex_1600.txt &
## Age Problem
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet34/N_100/Age --exp_name ResNet34_Age_HCP_IXI -b 8 --nb_folds 10 --net resnet34 --db healthy --sampler random --labels age --stratify_label age --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 100 &> resnet34_age_100.txt &
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet34/N_300/Age --exp_name ResNet34_Age_HCP_IXI -b 8 --nb_folds 10 --net resnet34 --db healthy --sampler random --labels age --stratify_label age --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 300 &> resnet34_age_300.txt &
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet34/N_500/Age --exp_name ResNet34_Age_HCP_IXI -b 8 --nb_folds 5 --net resnet34 --db healthy --sampler random --labels age --stratify_label age --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 500 &> resnet34_age_500.txt &
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet34/N_1000/Age --exp_name ResNet34_Age_HCP_IXI -b 8 --nb_folds 5 --net resnet34 --db healthy --sampler random --labels age --stratify_label age --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 1000 &> resnet34_age_1000.txt &
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet34/N_1600/Age --exp_name ResNet34_Age_HCP_IXI -b 8 --nb_folds 1 --net resnet34 --db healthy --sampler random --labels age --stratify_label age --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 1600 &> resnet34_age_1600.txt &

## AlphaWGAN
#CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/GAN/alpha_WGAN/age_prediction/No_Augmentation/With_KL --exp_name Alpha_WGAN_Age_HCP_IXI_scheduling_zero_gp_linear_pred -b 6 --nb_folds 1 --net alpha_wgan --lr 1e-4 --nb_epochs_per_saving 10 --db healthy --sampler random --labels age --nb_epochs 100  &> alpha_wgan_linear_age_pred.txt &

## PsyNet
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/scz_prediction/Benchmark_Transfer/GAN/Basic_With_Flip --exp_name PsyNet_AlphaWGAN_Finetuning -b 8 --nb_folds 1 --net psy_net --lr 1e-4 --nb_epochs_per_saving 10 --db scz_kfolds --sampler weighted_random --labels diagnosis --stratify_label diagnosis --with_test --nb_epochs 100 --pretrained_path /neurospin/psy_sbox/bd261576/checkpoints/GAN/alpha_WGAN/age_prediction/No_Augmentation/With_KL/Alpha_WGAN_Age_HCP_IXI_scheduling_zero_gp_0_epoch_99.pth &> psy_net.txt &


CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/scz_prediction/Benchmark_Transfer/No_Pretraining/schizconnect_vip_prague/ResNet34 --exp_name ResNet34_dx_Flip -b 8 --nb_folds 1 --net resnet34 --db tiny_scz_kfolds --sampler weighted_random --stratify_label diagnosis --labels diagnosis --with_test --lr 1e-4 --nb_epochs_per_saving 10 --nb_epochs 100 &> test_resnet34_dx_no_pretrainining.txt &
#CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/scz_prediction/Benchmark_Transfer/Sex_Age_Pretraining/schizconnect_vip_prague/ResNet34 --exp_name ResNet34_dx_Flip -b 8 --nb_folds 1 --net resnet34 --db tiny_scz_kfolds --sampler random --labels diagnosis --with_test --lr 1e-4 --pretrained_path /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet34/N_1600/ResNet34_Age_Sex_WithoutFC_0_epoch_99.pth --nb_epochs_per_saving 10 --nb_epochs 100 &> test_resnet34_dx_sex_age_pretrainining.txt &
#CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/scz_prediction/Benchmark_Transfer/Action_Recognition_Pretraining/schizonnect_vip_prague/ResNet34 --exp_name ResNet34_dx_Flip -b 8 --nb_folds 1 --net resnet34 --db tiny_scz_kfolds --sampler random --labels diagnosis --with_test --lr 1e-4 --pretrained_path /neurospin/psy_sbox/bd261576/checkpoints/pretrained_3D_resnet/resnet-34-without-fc.pth --nb_epochs_per_saving 10 --nb_epochs 100 &> test_resnet34_dx_kinetics_pretrainining.txt &
