main=~/PycharmProjects/pynet/main.py

## Sex, Age, Dx Bench

#CUDA_VISIBLE_DEVICES=2 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNeXt/Sex --exp_name ResNeXt_Sex_HCP_IXI -b 8 --nb_folds 1 --net resnext50 --db healthy --sampler random --labels sex --metrics roc_auc balanced_accuracy --with_test --lr 1e-4 --nb_epochs_per_saving 1 --nb_epochs 100 &> resneXt.txt &
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet18/Sex --exp_name ResNet18_Sex_HCP_IXI -b 8 --nb_folds 1 --net resnet18 --db healthy --sampler random --labels sex --metrics roc_auc balanced_accuracy --with_test --lr 1e-4 --nb_epochs_per_saving 1 --nb_epochs 100 &> resnet18.txt &
#CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet34/Sex --exp_name Full_ResNet34_Sex_HCP_IXI -b 8 --nb_folds 1 --net resnet34 --db healthy --sampler random --labels sex --metrics roc_auc balanced_accuracy --with_test --lr 1e-4 --nb_epochs_per_saving 1 --nb_epochs 100 &> resnet34_sex.txt &
#CUDA_VISIBLE_DEVICES=2 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet50/Sex --exp_name ResNet50_Sex_HCP_IXI -b 8 --nb_folds 1 --net resnet50 --db healthy --sampler random --labels sex --with_test --metrics roc_auc balanced_accuracy --lr 1e-4 --nb_epochs_per_saving 1 --nb_epochs 100 &> resnet50.txt &
#CUDA_VISIBLE_DEVICES=3 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet101/Sex --exp_name ResNet101_Sex_HCP_IXI -b 8 --nb_folds 1 --net resnet101 --db healthy --sampler random --labels sex --with_test --metrics roc_auc balanced_accuracy --lr 1e-4 --nb_epochs_per_saving 1 --nb_epochs 100 &> resnet101.txt &
#CUDA_VISIBLE_DEVICES=3 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/DenseNet/Age --exp_name DenseNet_Age_HCP_IXI -b 8 --nb_folds 1 --net densenet121 --db healthy --sampler random --labels age --test --lr 1e-4 --nb_epochs_per_saving 1 --nb_epochs 100 &> densenet121.txt &
#CUDA_VISIBLE_DEVICES=2 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ColeNet/Sex --exp_name Full_ColeNet_Sex_HCP_IXI -b 8 --nb_folds 1 --net cole_net --db healthy --sampler random --labels sex --with_test --metrics roc_auc balanced_accuracy --lr 1e-4 --nb_epochs_per_saving 1 --nb_epochs 100 &> sex_colenet.txt &
#CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/VGG/VGG11/Sex --exp_name VGG11_Sex_HCP_IXI -b 8 --nb_folds 1 --net vgg11 --db healthy --sampler random --labels sex --with_test --lr 1e-4 --metrics roc_auc balanced_accuracy --nb_epochs_per_saving 1 --nb_epochs 100 &> vgg11.txt &

# TODO
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/VGG/VGG16/Sex --exp_name VGG16_Sex_HCP_IXI -b 8 --nb_folds 1 --net vgg16 --db healthy --sampler random --labels sex --with_test --lr 1e-4 --metrics roc_auc balanced_accuracy --nb_epochs_per_saving 1 --nb_epochs 100 &> vgg16.txt &

#CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/VGG/VGG11/Dx --exp_name VGG11_Dx_SCZ_VIP -b 8 --nb_folds 5 --net vgg11 --db tiny_scz_kfolds --sampler random --stratify_label diagnosis --labels diagnosis --test --metrics roc_auc balanced_accuracy --lr 1e-4 --nb_epochs_per_saving 1 --nb_epochs 50 &> vgg11_dx.txt &
#CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ColeNet/Dx --exp_name Full_ColeNet_Dx_SCZ_VIP -b 8 --nb_folds 5 --net cole_net --db tiny_scz_kfolds --sampler random --stratify_label diagnosis --labels diagnosis --test --metrics roc_auc balanced_accuracy --lr 1e-4 --nb_epochs_per_saving 1 --nb_epochs 50 &> dx_colenet.txt &
#CUDA_VISIBLE_DEVICES=2 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNeXt/Dx --exp_name ResNeXt_Dx_SCZ_VIP -b 8 --nb_folds 5 --net resnext50 --db tiny_scz_kfolds --sampler random --stratify_label diagnosis --labels diagnosis --metrics roc_auc balanced_accuracy --test --lr 1e-4 --nb_epochs_per_saving 1 --nb_epochs 50 &> resneXt_dx.txt &
#CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet18/Dx --exp_name ResNet18_Dx_SCZ_VIP -b 8 --nb_folds 5 --net resnet18 --db tiny_scz_kfolds --sampler random --stratify_label diagnosis --labels diagnosis --metrics roc_auc balanced_accuracy --test --lr 1e-4 --nb_epochs_per_saving 1 --nb_epochs 50 &> resnet18.txt &
#CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet34/Dx --exp_name Full_ResNet34_Dx_SCZ_VIP -b 8 --nb_folds 5 --net resnet34 --db tiny_scz_kfolds --sampler random --stratify_label diagnosis --labels diagnosis --metrics roc_auc balanced_accuracy --test --lr 1e-4 --nb_epochs_per_saving 1 --nb_epochs 50 &> resnet34_dx.txt &
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet50/Dx --exp_name ResNet50_Dx_SCZ_VIP -b 8 --nb_folds 5 --net resnet50 --db tiny_scz_kfolds --sampler random --stratify_label diagnosis --labels diagnosis --test --metrics roc_auc balanced_accuracy --lr 1e-4 --nb_epochs_per_saving 1 --nb_epochs 50 &> resnet50.txt &
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet101/Dx --exp_name ResNet101_Dx_SCZ_VIP -b 8 --nb_folds 5 --net resnet101 --db tiny_scz_kfolds --sampler random --stratify_label diagnosis --labels diagnosis --test --metrics roc_auc balanced_accuracy --lr 1e-4 --nb_epochs_per_saving 1 --nb_epochs 50 &> resnet101.txt &
#CUDA_VISIBLE_DEVICES=3 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/VGG/VGG16/Dx --exp_name VGG16_Dx_SCZ_VIP -b 8 --nb_folds 5 --net vgg16 --db tiny_scz_kfolds --sampler random --stratify_label diagnosis --labels diagnosis --test --metrics roc_auc balanced_accuracy --lr 1e-4 --nb_epochs_per_saving 1 --nb_epochs 50 &> vgg16.txt &

## MC-Dropout comparison


#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/DenseNet/Dx/Dropout/p_0.5 --exp_name DenseNet_Dx_SCZ_VIP -b 8 --nb_folds 5 --net densenet121 --db tiny_scz_kfolds --sampler random --gamma_scheduler 0.2 --stratify_label diagnosis --labels diagnosis --dropout 0.5 --bayesian --test MC --loss BCE --metrics roc_auc balanced_accuracy --lr 1e-4 --nb_epochs_per_saving 50 --nb_epochs 50 &> densenet_dx_drop0.5.txt &
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/DenseNet/Dx/Dropout/p_0.2 --exp_name DenseNet_Dx_SCZ_VIP -b 8 --nb_folds 5 --net densenet121 --db tiny_scz_kfolds --sampler random --gamma_scheduler 0.2 --stratify_label diagnosis --labels diagnosis --dropout 0.2 --bayesian --test MC --loss BCE --metrics roc_auc balanced_accuracy --lr 1e-4 --nb_epochs_per_saving 50 --nb_epochs 50 &> densenet_dx_drop0.2.txt &
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/DenseNet/Dx/Dropout/Concrete_Dropout --exp_name DenseNet_Dx_SCZ_VIP -b 4 --nb_folds 5 --net densenet121 --db tiny_scz_kfolds --sampler random --gamma_scheduler 0.2 --stratify_label diagnosis --labels diagnosis --concrete_dropout  --test MC --loss BCE_concrete_dropout --metrics roc_auc balanced_accuracy --lr 1e-4 --nb_epochs_per_saving 50 --nb_epochs 50 &> densenet_dx_concrete_dropout.txt &

#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ColeNet/Dx/Dropout/Concrete_Dropout --exp_name ColeNet_Dx_SCZ_VIP -b 4 --nb_folds 5 --net cole_net --db tiny_scz_kfolds --sampler random --gamma_scheduler 0.2 --stratify_label diagnosis --labels diagnosis --concrete_dropout --test MC --loss BCE_concrete_dropout --metrics roc_auc balanced_accuracy --lr 1e-4 --nb_epochs_per_saving 50 --nb_epochs 50 &> colenet_dx_concrete_dropout.txt &


# Transfer Learning

#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/scz_prediction/Benchmark_Transfer/Age_Pretraining/schizconnect_vip/DenseNet --exp_name DenseNet_Dx_SCZ_VIP -b 4 --gamma_scheduler 0.2 --loss BCE --nb_folds 5 --net densenet121 --db tiny_scz_kfolds --sampler random --stratify_label diagnosis --labels diagnosis --test with_training --metrics roc_auc balanced_accuracy --lr 1e-4 --nb_epochs_per_saving 50 --pretrained_path /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/DenseNet/Age/DenseNet_Age_HCP_IXI_0_epoch_99_without_classifier.pth --nb_epochs 50 &> densenet121_age_pretrained.txt &
CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/scz_prediction/Benchmark_Transfer/Age_Pretraining/schizconnect_vip/DenseNet --exp_name DenseNet_Dx_SCZ_VIP -b 4 --gamma_scheduler 0.2 --loss BCE --nb_folds 5 --net densenet121_block4 --db tiny_scz_kfolds --sampler random --stratify_label diagnosis --labels diagnosis --test MC --metrics roc_auc balanced_accuracy --lr 1e-4 --nb_epochs 50 &> test__densenet121_block1.txt &


## LightResNet34
#CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/LightResNet34/N_100 --exp_name Light_ResNet34_Age_HCP_IXI -b 8 --nb_folds 10 --net light_resnet34 --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 100 --N_train_max 100 &> light_resnet34_N100.txt &
#CUDA_VISIBLE_DEVICES=2 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/LightResNet34/N_300 --exp_name Light_ResNet34_Age_HCP_IXI -b 8 --nb_folds 10 --net light_resnet34 --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 100 --N_train_max 300 &> light_resnet34_N300.txt &
#CUDA_VISIBLE_DEVICES=3 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/LightResNet34/N_500 --exp_name Light_ResNet34_Age_HCP_IXI -b 8 --nb_folds 5 --net light_resnet34 --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 100 --N_train_max 500 &> light_resnet34_N500.txt &
#

## Robustness curves
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/DenseNet/Age --exp_name DenseNet_Age_HCP_IXI -b 8 --nb_folds 1 --net densenet121 --db healthy --sampler random --labels age --test robustness --lr 1e-4 --nb_epochs_per_saving 1 --nb_epochs 100 &> densenet121.txt &
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ColeNet/Age --exp_name Full_ColeNet_Age_HCP_IXI -b 8 --nb_folds 1 --net cole_net --db healthy --sampler random --labels age --test robustness --lr 1e-4 --nb_epochs_per_saving 1 --nb_epochs 100 &> colenet.txt &
#CUDA_VISIBLE_DEVICES=2 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNeXt/Age --exp_name ResNeXt_Age_HCP_IXI -b 8 --nb_folds 1 --net resnext50 --db healthy --sampler random --labels age --test robustness --lr 1e-4 --nb_epochs_per_saving 1 --nb_epochs 100 &> resnext.txt &
#CUDA_VISIBLE_DEVICES=2 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet18/Age --exp_name ResNet18_Age_HCP_IXI -b 8 --nb_folds 1 --net resnet18 --db healthy --sampler random --labels age --test robustness --lr 1e-4 --nb_epochs_per_saving 1 --nb_epochs 100 &> resnet18.txt &
#CUDA_VISIBLE_DEVICES=2 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet50/Age --exp_name ResNet50_Age_HCP_IXI -b 8 --nb_folds 1 --net resnet50 --db healthy --sampler random --labels age --test robustness --lr 1e-4 --nb_epochs_per_saving 1 --nb_epochs 100 &> resnet50.txt &
#CUDA_VISIBLE_DEVICES=2 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet34/Age --exp_name Full_ResNet34_Age_HCP_IXI -b 8 --nb_folds 1 --net resnet34 --db healthy --sampler random --labels age --test robustness --lr 1e-4 --nb_epochs_per_saving 1 --nb_epochs 100 &> resnet34.txt &
#CUDA_VISIBLE_DEVICES=2 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet101/Age --exp_name ResNet101_Age_HCP_IXI -b 8 --nb_folds 1 --net resnet101 --db healthy --sampler random --labels age --test robustness --lr 1e-4 --nb_epochs_per_saving 1 --nb_epochs 100 &> resnet101.txt &
#CUDA_VISIBLE_DEVICES=2 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/VGG/VGG11/Age --exp_name VGG11_Age_HCP_IXI -b 8 --nb_folds 1 --net vgg11 --db healthy --sampler random --labels age --test robustness --lr 1e-4 --nb_epochs_per_saving 1 --nb_epochs 100 &> vgg11.txt &

#CUDA_VISIBLE_DEVICES=2 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/DenseNet/Sex --exp_name DenseNet_Sex_HCP_IXI -b 8 --nb_folds 1 --net densenet121 --db healthy --sampler random --labels sex --test robustness --lr 1e-4 --nb_epochs_per_saving 1 --nb_epochs 100 &> densenet121.txt &
#CUDA_VISIBLE_DEVICES=2 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ColeNet/Sex --exp_name Full_ColeNet_Sex_HCP_IXI -b 8 --nb_folds 1 --net cole_net --db healthy --sampler random --labels sex --test robustness --lr 1e-4 --nb_epochs_per_saving 1 --nb_epochs 100 &> colenet.txt &
#CUDA_VISIBLE_DEVICES=2 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNeXt/Sex --exp_name ResNeXt_Sex_HCP_IXI -b 8 --nb_folds 1 --net resnext50 --db healthy --sampler random --labels sex --test robustness --lr 1e-4 --nb_epochs_per_saving 1 --nb_epochs 100 &> resnext.txt &
#CUDA_VISIBLE_DEVICES=2 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet18/Sex --exp_name ResNet18_Sex_HCP_IXI -b 8 --nb_folds 1 --net resnet18 --db healthy --sampler random --labels sex --test robustness --lr 1e-4 --nb_epochs_per_saving 1 --nb_epochs 100 &> resnet18.txt &
#CUDA_VISIBLE_DEVICES=3 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet50/Sex --exp_name ResNet50_Sex_HCP_IXI -b 8 --nb_folds 1 --net resnet50 --db healthy --sampler random --labels sex --test robustness --lr 1e-4 --nb_epochs_per_saving 1 --nb_epochs 100 &> resnet50.txt &
#CUDA_VISIBLE_DEVICES=3 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet34/Sex --exp_name Full_ResNet34_Sex_HCP_IXI -b 8 --nb_folds 1 --net resnet34 --db healthy --sampler random --labels sex --test robustness --lr 1e-4 --nb_epochs_per_saving 1 --nb_epochs 100 &> resnet34.txt &
#CUDA_VISIBLE_DEVICES=3 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet101/Sex --exp_name ResNet101_Sex_HCP_IXI -b 8 --nb_folds 1 --net resnet101 --db healthy --sampler random --labels sex --test robustness --lr 1e-4 --nb_epochs_per_saving 1 --nb_epochs 100 &> resnet101.txt &
#CUDA_VISIBLE_DEVICES=3 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/VGG/VGG11/Sex --exp_name VGG11_Sex_HCP_IXI -b 8 --nb_folds 1 --net vgg11 --db healthy --sampler random --labels sex --test robustness --lr 1e-4 --nb_epochs_per_saving 1 --nb_epochs 100 &> vgg11.txt &

#CUDA_VISIBLE_DEVICES=2 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/DenseNet/Dx --exp_name DenseNet_Dx_SCZ_VIP -b 8 --nb_folds 5 --net densenet121 --db tiny_scz_kfolds --sampler random --labels diagnosis --test robustness --lr 1e-4 --nb_epochs_per_saving 1 --nb_epochs 50 &> densenet121.txt &
#CUDA_VISIBLE_DEVICES=2 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ColeNet/Dx --exp_name Full_ColeNet_Dx_SCZ_VIP -b 8 --nb_folds 5 --net cole_net --db tiny_scz_kfolds --sampler random --labels diagnosis --test robustness --lr 1e-4 --nb_epochs_per_saving 1 --nb_epochs 50 &> colenet.txt &
#CUDA_VISIBLE_DEVICES=2 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNeXt/Dx --exp_name ResNeXt_Dx_SCZ_VIP -b 8 --nb_folds 5 --net resnext50 --db tiny_scz_kfolds --sampler random --labels diagnosis --test robustness --lr 1e-4 --nb_epochs_per_saving 1 --nb_epochs 50 &> resnext.txt &
#CUDA_VISIBLE_DEVICES=2 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet18/Dx --exp_name ResNet18_Dx_SCZ_VIP -b 8 --nb_folds 5 --net resnet18 --db tiny_scz_kfolds --sampler random --labels diagnosis --test robustness --lr 1e-4 --nb_epochs_per_saving 1 --nb_epochs 50 &> resnet18.txt &
#CUDA_VISIBLE_DEVICES=3 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet50/Dx --exp_name ResNet50_Dx_SCZ_VIP -b 8 --nb_folds 5 --net resnet50 --db tiny_scz_kfolds --sampler random --labels diagnosis --test robustness --lr 1e-4 --nb_epochs_per_saving 1 --nb_epochs 50 &> resnet50.txt &
#CUDA_VISIBLE_DEVICES=3 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet34/Dx --exp_name Full_ResNet34_Dx_SCZ_VIP -b 8 --nb_folds 5 --net resnet34 --db tiny_scz_kfolds --sampler random --labels diagnosis --test robustness --lr 1e-4 --nb_epochs_per_saving 1 --nb_epochs 50 &> resnet34.txt &
#CUDA_VISIBLE_DEVICES=3 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet101/Dx --exp_name ResNet101_Dx_SCZ_VIP -b 8 --nb_folds 5 --net resnet101 --db tiny_scz_kfolds --sampler random --labels diagnosis --test robustness --lr 1e-4 --nb_epochs_per_saving 1 --nb_epochs 50 &> resnet101.txt &
#CUDA_VISIBLE_DEVICES=3 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/VGG/VGG11/Dx --exp_name VGG11_Dx_SCZ_VIP -b 8 --nb_folds 5 --net vgg11 --db tiny_scz_kfolds --sampler random --labels diagnosis --test robustness --lr 1e-4 --nb_epochs_per_saving 1 --nb_epochs 50 &> vgg11.txt &



## Learning Curves
#ColeNet
#Sex problem
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ColeNet/N_100/Sex --exp_name ColeNet_Sex_HCP_IXI -b 8 --nb_folds 10 --net cole_net --db healthy --sampler random --labels sex --stratify_label site --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 100 &> colenet_sex_100.txt &
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ColeNet/N_300/Sex --exp_name ColeNet_Sex_HCP_IXI -b 8 --nb_folds 10 --net cole_net --db healthy --sampler random --labels sex --stratify_label site --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --folds 5 6 7 8 9 --N_train_max 300 &> colenet_sex_300.txt &
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ColeNet/N_500/Sex --exp_name ColeNet_Sex_HCP_IXI -b 8 --nb_folds 5 --net cole_net --db healthy --sampler random --labels sex --stratify_label site --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --folds 3 4 --N_train_max 500 &> colenet_sex_500.txt &
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ColeNet/N_1000/Sex --exp_name ColeNet_Sex_HCP_IXI -b 8 --nb_folds 5 --net cole_net --db healthy --sampler random --labels sex --stratify_label site --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --folds 2 3 4 --N_train_max 1000 &> colenet_sex_1000.txt &
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ColeNet/N_1600/Sex --exp_name ColeNet_Sex_HCP_IXI -b 8 --nb_folds 1 --net cole_net --db healthy --sampler random --labels sex --stratify_label site --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 1600 &> colenet_sex_1600.txt &
## Age problem
#CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ColeNet/N_100/Age --exp_name ColeNet_Age_HCP_IXI -b 8 --nb_folds 10 --net cole_net --db healthy --sampler random --labels age --stratify_label age --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 100 &> colenet_age_100.txt &
#CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ColeNet/N_300/Age --exp_name ColeNet_Age_HCP_IXI -b 8 --nb_folds 10 --net cole_net --db healthy --sampler random --labels age --stratify_label age --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --folds 5 6 7 8 9 --N_train_max 300 &> colenet_age_300.txt &
#CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ColeNet/N_500/Age --exp_name ColeNet_Age_HCP_IXI -b 8 --nb_folds 5 --net cole_net --db healthy --sampler random --labels age --stratify_label age --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --folds 3 4 --N_train_max 500 &> colenet_age_500.txt &
#CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ColeNet/N_1000/Age --exp_name ColeNet_Age_HCP_IXI -b 8 --nb_folds 5 --net cole_net --db healthy --sampler random --labels age --stratify_label age --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --folds 2 3 4 --N_train_max 1000 &> colenet_age_1000.txt &
#CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ColeNet/N_1600/Age --exp_name ColeNet_Age_HCP_IXI -b 8 --nb_folds 1 --net cole_net --db healthy --sampler random --labels age --stratify_label age --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 1600 &> colenet_age_1600.txt &
## Dx problem
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ColeNet/N_100/Dx --exp_name ColeNet_Dx_SCZ_VIP -b 8 --nb_folds 10 --net cole_net --db tiny_scz_kfolds --gamma_scheduler 0.2 --sampler random --labels diagnosis --loss BCE --stratify_label diagnosis --test with_training --metrics roc_auc balanced_accuracy --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 100 &> colenet_dx_100.txt &
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ColeNet/N_300/Dx --exp_name ColeNet_Dx_SCZ_VIP -b 8 --nb_folds 10 --net cole_net --db tiny_scz_kfolds --gamma_scheduler 0.2 --sampler random --labels diagnosis --loss BCE --stratify_label diagnosis --test with_training --metrics roc_auc balanced_accuracy --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 300 &> colenet_dx_300.txt &
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ColeNet/N_500/Dx --exp_name ColeNet_Dx_SCZ_VIP -b 8 --nb_folds 5 --net cole_net --db tiny_scz_kfolds --gamma_scheduler 0.2 --sampler random --labels diagnosis --loss BCE --stratify_label diagnosis --test with_training --metrics roc_auc balanced_accuracy --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 500 &> colenet_dx_500.txt &

# DenseNet
#Sex problem
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/DenseNet/N_100/Sex --exp_name DenseNet_Sex_HCP_IXI -b 8 --nb_folds 10 --net densenet121 --db healthy --sampler random --labels sex --stratify_label site --test with_training --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 100 &> densenet_sex_100.txt &
#CUDA_VISIBLE_DEVICES=2 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/DenseNet/N_300/Sex --exp_name DenseNet_Sex_HCP_IXI -b 8 --nb_folds 10 --net densenet121 --db healthy --sampler random --labels sex --stratify_label site --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --folds 5 6 7 8 9 --N_train_max 300 &> densenet_sex_300.txt &
#CUDA_VISIBLE_DEVICES=2 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/DenseNet/N_500/Sex --exp_name DenseNet_Sex_HCP_IXI -b 8 --nb_folds 5 --net densenet121 --db healthy --sampler random --labels sex --stratify_label site --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --folds 4 --N_train_max 500 &> densenet_sex_500.txt &
#CUDA_VISIBLE_DEVICES=2 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/DenseNet/N_1000/Sex --exp_name DenseNet_Sex_HCP_IXI -b 8 --nb_folds 5 --net densenet121 --db healthy --sampler random --labels sex --stratify_label site --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --folds 2 3 4 --N_train_max 1000 &> densenet_sex_1000.txt &
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/DenseNet/N_1600/Sex --exp_name DenseNet_Sex_HCP_IXI -b 8 --nb_folds 1 --net densenet121 --db healthy --sampler random --labels sex --stratify_label site --test with_training --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 1600 &> densenet_sex_1600.txt &
## Age problem
#CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/DenseNet/N_100/Age --exp_name DenseNet_Age_HCP_IXI -b 8 --nb_folds 10 --net densenet121 --db healthy --sampler random --labels age --stratify_label age --test with_training --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 100 &> densenet_age_100.txt &
#CUDA_VISIBLE_DEVICES=3 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/DenseNet/N_300/Age --exp_name DenseNet_Age_HCP_IXI -b 8 --nb_folds 10 --net densenet121 --db healthy --sampler random --labels age --stratify_label age --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --folds 5 6 7 8 9 --N_train_max 300 &> densenet_age_300.txt &
#CUDA_VISIBLE_DEVICES=3 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/DenseNet/N_500/Age --exp_name DenseNet_Age_HCP_IXI -b 8 --nb_folds 5 --net densenet121 --db healthy --sampler random --labels age --stratify_label age --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --folds 4 --N_train_max 500 &> densenet_age_500.txt &
#CUDA_VISIBLE_DEVICES=3 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/DenseNet/N_1000/Age --exp_name DenseNet_Age_HCP_IXI -b 8 --nb_folds 5 --net densenet121 --db healthy --sampler random --labels age --stratify_label age --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --folds 2 3 4 --N_train_max 1000 &> densenet_age_1000.txt &
#CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/DenseNet/N_1600/Age --exp_name DenseNet_Age_HCP_IXI -b 8 --nb_folds 1 --net densenet121 --db healthy --sampler random --labels age --stratify_label age --test with_training --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 1600 &> densenet_age_1600.txt &
## Dx problem
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/DenseNet/N_100/Dx --exp_name DenseNet_Dx_SCZ_VIP -b 8 --nb_folds 10 --net densenet121 --db tiny_scz_kfolds --gamma_scheduler 0.2 --sampler random --labels diagnosis --loss BCE --stratify_label diagnosis --test with_training --metrics roc_auc balanced_accuracy --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 100 &> densenet_dx_100.txt &
#CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/DenseNet/N_300/Dx --exp_name DenseNet_Dx_SCZ_VIP -b 8 --nb_folds 10 --net densenet121 --db tiny_scz_kfolds --sampler random --labels diagnosis --stratify_label diagnosis --test with_training --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 300 &> densenet_dx_300.txt &
#CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/DenseNet/N_500/Dx --exp_name DenseNet_Dx_SCZ_VIP -b 8 --nb_folds 5 --net densenet121 --db tiny_scz_kfolds --sampler random --labels diagnosis --stratify_label diagnosis --test with_training --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 500 &> densenet_dx_500.txt &


### ResNet34
# Sex problem
#CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet34/N_100/Sex --exp_name ResNet34_Sex_HCP_IXI -b 8 --nb_folds 10 --net resnet34 --db healthy --sampler random --labels sex --stratify_label site --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 100 &> resnet34_sex_100.txt &
#CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet34/N_300/Sex --exp_name ResNet34_Sex_HCP_IXI -b 8 --nb_folds 10 --net resnet34 --db healthy --sampler random --labels sex --stratify_label site --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 300 &> resnet34_sex_300.txt &
#CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet34/N_500/Sex --exp_name ResNet34_Sex_HCP_IXI -b 8 --nb_folds 5 --net resnet34 --db healthy --sampler random --labels sex --stratify_label site --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 500 &> resnet34_sex_500.txt &
#CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet34/N_1000/Sex --exp_name ResNet34_Sex_HCP_IXI -b 8 --nb_folds 5 --net resnet34 --db healthy --sampler random --labels sex --stratify_label site --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 1000 &> resnet34_sex_1000.txt &
##CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet34/N_1600/Sex --exp_name ResNet34_Sex_HCP_IXI -b 8 --nb_folds 1 --net resnet34 --db healthy --sampler random --labels sex --stratify_label site --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 1600 &> resnet34_sex_1600.txt &
## Age Problem
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet34/N_100/Age --exp_name ResNet34_Age_HCP_IXI -b 8 --nb_folds 10 --net resnet34 --db healthy --sampler random --labels age --stratify_label age --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 100 &> resnet34_age_100.txt &
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet34/N_300/Age --exp_name ResNet34_Age_HCP_IXI -b 8 --nb_folds 10 --net resnet34 --db healthy --sampler random --labels age --stratify_label age --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 300 &> resnet34_age_300.txt &
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet34/N_500/Age --exp_name ResNet34_Age_HCP_IXI -b 8 --nb_folds 5 --net resnet34 --db healthy --sampler random --labels age --stratify_label age --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 500 &> resnet34_age_500.txt &
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet34/N_1000/Age --exp_name ResNet34_Age_HCP_IXI -b 8 --nb_folds 5 --net resnet34 --db healthy --sampler random --labels age --stratify_label age --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 1000 &> resnet34_age_1000.txt &
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet34/N_1600/Age --exp_name ResNet34_Age_HCP_IXI -b 8 --nb_folds 1 --net resnet34 --db healthy --sampler random --labels age --stratify_label age --with_test --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 1600 &> resnet34_age_1600.txt &
## Dx Problem
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet34/N_100/Dx --exp_name ResNet34_Dx_SCZ_VIP -b 8 --nb_folds 10 --net resnet34 --db tiny_scz_kfolds --gamma_scheduler 0.2 --sampler random --labels diagnosis --stratify_label diagnosis --loss BCE --test with_training --metrics roc_auc balanced_accuracy --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 100 &> resnet34_dx_100.txt &
#CUDA_VISIBLE_DEVICES=2 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet34/N_300/Dx --exp_name ResNet34_Dx_SCZ_VIP -b 8 --nb_folds 10 --net resnet34 --db tiny_scz_kfolds --sampler random --labels age --stratify_label age --test with_training --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 300 &> resnet34_dx_300.txt &
#CUDA_VISIBLE_DEVICES=2 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet34/N_500/Dx --exp_name ResNet34_Dx_SCZ_VIP -b 8 --nb_folds 5 --net resnet34 --db tiny_scz_kfolds --sampler random --labels age --stratify_label age --test with_trainingt --lr 1e-4 --nb_epochs_per_saving 100 --nb_epochs 300 --test_all_epochs --N_train_max 500 &> resnet34_dx_500.txt &

## AlphaWGAN
#CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/GAN/alpha_WGAN/age_prediction/No_Augmentation/With_KL --exp_name Alpha_WGAN_Age_HCP_IXI_scheduling_zero_gp_linear_pred -b 6 --nb_folds 1 --net alpha_wgan --lr 1e-4 --nb_epochs_per_saving 10 --db healthy --sampler random --labels age --nb_epochs 100  &> alpha_wgan_linear_age_pred.txt &

## PsyNet
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/scz_prediction/Benchmark_Transfer/GAN/Basic_With_Flip --exp_name PsyNet_AlphaWGAN_Finetuning -b 8 --nb_folds 1 --net psy_net --lr 1e-4 --nb_epochs_per_saving 10 --db scz_kfolds --sampler weighted_random --labels diagnosis --stratify_label diagnosis --with_test --nb_epochs 100 --pretrained_path /neurospin/psy_sbox/bd261576/checkpoints/GAN/alpha_WGAN/age_prediction/No_Augmentation/With_KL/Alpha_WGAN_Age_HCP_IXI_scheduling_zero_gp_0_epoch_99.pth &> psy_net.txt &


#CUDA_VISIBLE_DEVICES=2 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/scz_prediction/Benchmark_Transfer/No_Pretraining/schizconnect_vip_prague/ResNet34 --exp_name ResNet34_dx_Flip_with_validation -b 8 --nb_folds 1 --net resnet34 --db tiny_scz --sampler weighted_random --stratify_label diagnosis --labels diagnosis --with_test --metrics balanced_accuracy roc_auc --lr 1e-4 --nb_epochs_per_saving 10 --nb_epochs 100 &> test_resnet34_dx_no_pretrainining.txt &
#CUDA_VISIBLE_DEVICES=1 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/scz_prediction/Benchmark_Transfer/Sex_Age_Pretraining/schizconnect_vip_prague/ResNet34 --exp_name ResNet34_dx_Flip -b 8 --nb_folds 1 --net resnet34 --db tiny_scz_kfolds --sampler weighted_random --stratify_label diagnosis --labels diagnosis --with_test --lr 1e-4 --pretrained_path /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet34/N_1600/ResNet34_Age_Sex_WithoutFC_0_epoch_99.pth --nb_epochs_per_saving 10 --nb_epochs 100 &> test_resnet34_dx_sex_age_pretrainining.txt &
#CUDA_VISIBLE_DEVICES=2 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/scz_prediction/Benchmark_Transfer/Action_Recognition_Pretraining/schizonnect_vip_prague/ResNet34 --exp_name ResNet34_dx_Flip -b 8 --nb_folds 1 --net resnet34 --db tiny_scz_kfolds --sampler weighted_random --stratify_label diagnosis --labels diagnosis --with_test --lr 1e-4 --pretrained_path /neurospin/psy_sbox/bd261576/checkpoints/pretrained_3D_resnet/r3d34_K_200ep-without-fc.pth --nb_epochs_per_saving 10 --nb_epochs 100 &> test_resnet34_dx_kinetics_pretrainining.txt &
#CUDA_VISIBLE_DEVICES=0 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/scz_prediction/Benchmark_Transfer/Age_Pretraining/schizonnect_vip_prague/ResNet34 --exp_name ResNet34_dx_Flip -b 8 --nb_folds 1 --net resnet34 --db tiny_scz_kfolds --sampler weighted_random --stratify_label diagnosis --labels diagnosis --with_test --lr 1e-4 --pretrained_path /neurospin/psy_sbox/bd261576/checkpoints/regression_age_sex/Benchmark_IXI_HCP/ResNet/ResNet34/N_1600/Age/ResNet34_Age_HCP_IXI_0_epoch_299.pth --nb_epochs_per_saving 10 --nb_epochs 100 &> test_resnet34_age_pretrainining.txt &
#CUDA_VISIBLE_DEVICES=2 python3 $main --checkpoint_dir /neurospin/psy_sbox/bd261576/checkpoints/scz_prediction/Benchmark_Transfer/Self_Supervision/schizonnect_vip_prague/ResNet34 --exp_name ResNet34_dx_Flip -b 8 --nb_folds 1 --net resnet34 --db tiny_scz_kfolds --sampler weighted_random --stratify_label diagnosis --labels diagnosis --with_test --lr 1e-4 --pretrained_path /neurospin/psy_sbox/bd261576/checkpoints/pretrained_3D_resnet/Self_Supervision/ResNet34_HCP_IXI_PatchInversion_0_epoch_75.pth  --nb_epochs_per_saving 10 --nb_epochs 100 &> test_resnet34_self_supervised_pretrainining.txt &


# CCA
#cca_analysis=~/PycharmProjects/pynet/CCA_analysis.py
#CUDA_VISIBLE_DEVICES=0 python3 $cca_analysis &> cca_analysis_complete.txt &


